name: research
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - matplotlib
  - torchvision
  - pytorch
  - pip:
      - opencv-python
      - scipy>=1.3.0
      - numpy>=1.13
      - Pillow>=6.1.0
