name: research

dependencies:
  - python=3.6
  - matplotlib
  - pip:
    - opencv-python
    - keras==2.1.4
    - tensorflow==1.6.0
    - scipy==1.3.0
    - numpy>=1.13
    - h5py==2.9.0
    - Pillow==6.1.0