name: research
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - matplotlib
  - torchvision=0.4.2
  - pytorch=1.3
  - pip:
      - opencv-python
      - scipy>=1.3.0
      - numpy>=1.16.4
      - Pillow>=6.1.0
      - pytorch-lightning>=0.5.3
